version: "3.9"

services:
  example:
    build: .
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - example
